# This is a basic workflow to help you get started with Actions

name: good-morning-mfe

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  blackduck-scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: wget -O ~/synopsys-detect-6.9.1.jar https://sig-repo.synopsys.com/bds-integrations-release/com/synopsys/integration/synopsys-detect/6.9.1/synopsys-detect-6.9.1.jar
      - run: java -jar ~/synopsys-detect-6.9.1.jar --blackduck.url=https://blackduck.ironsrc.net --blackduck.api.token=${{ secrets.BLACKDUCK_TOKEN }} --detect.blackduck.signature.scanner.individual.file.matching=NONE --blackduck.trust.cert=true --detect.project.user.groups=blackduck-supersonic-studios --detect.project.name=supersonic-studios-`pwd | awk -F / '{print $NF}'` --detect.project.version.distribution=EXTERNAL
